
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action FileAction;
	private global::Gtk.Action LoadPrefsAction;
	private global::Gtk.Action SavePrefsAction;
	private global::Gtk.Action QuitAction;
	private global::Gtk.Action EditAction;
	private global::Gtk.Action UserDetailsAction;
	private global::Gtk.Action PreferencesAction;
	private global::Gtk.Action GenerateAction;
	private global::Gtk.Action KeyAction;
	private global::Gtk.Action CertificateAction;
	private global::Gtk.Action HelpAction;
	private global::Gtk.Action ClearStatusBarAction;
	private global::Gtk.Action rubbishAction;
	private global::Gtk.Action AboutAction;
	private global::Gtk.Action StripPassphraseAction;
	private global::Gtk.Action ToolsAction;
	private global::Gtk.Action WorkingDirectoryAction;
	private global::Gtk.Action ViewCertificateAction;
	private global::Gtk.Action CheckDiskAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.MenuBar mainmenubar;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Image image29;
	private global::Gtk.Label label1;
	private global::Gtk.Image image12;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.HBox hbox7;
	private global::Gtk.Label label2;
	private global::Gtk.VBox vbox3;
	private global::Gtk.VBox vbox5;
	private global::Gtk.HSeparator hseparator4;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox8;
	private global::Gtk.Fixed fixed6;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Label label3;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Label lblKeyFileLocation;
	private global::Gtk.Label label4;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label lblCertFileLocation;
	private global::Gtk.Label GtkLabel6;
	private global::Gtk.Fixed fixed5;
	private global::Gtk.HBox hbox9;
	private global::Gtk.Fixed fixed8;
	private global::Gtk.Frame frame2;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.VBox vbox7;
	private global::Gtk.Fixed fixed3;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Entry ebCommonName;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.HBox hbox10;
	private global::Gtk.Fixed fixed9;
	private global::Gtk.Button btnGenerateCert;
	private global::Gtk.Fixed fixed11;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label GtkLabel10;
	private global::Gtk.Fixed fixed7;
	private global::Gtk.HSeparator hseparator2;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button button1;
	private global::Gtk.Statusbar statusbar1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.LoadPrefsAction = new global::Gtk.Action ("LoadPrefsAction", global::Mono.Unix.Catalog.GetString ("Load Prefs"), null, null);
		this.LoadPrefsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load Prefs");
		w1.Add (this.LoadPrefsAction, null);
		this.SavePrefsAction = new global::Gtk.Action ("SavePrefsAction", global::Mono.Unix.Catalog.GetString ("Save Prefs"), null, null);
		this.SavePrefsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save Prefs");
		w1.Add (this.SavePrefsAction, null);
		this.QuitAction = new global::Gtk.Action ("QuitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, null);
		this.QuitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.QuitAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.UserDetailsAction = new global::Gtk.Action ("UserDetailsAction", global::Mono.Unix.Catalog.GetString ("User Details"), null, null);
		this.UserDetailsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("User Details");
		w1.Add (this.UserDetailsAction, null);
		this.PreferencesAction = new global::Gtk.Action ("PreferencesAction", global::Mono.Unix.Catalog.GetString ("Preferences"), null, null);
		this.PreferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
		w1.Add (this.PreferencesAction, null);
		this.GenerateAction = new global::Gtk.Action ("GenerateAction", global::Mono.Unix.Catalog.GetString ("Generate"), null, null);
		this.GenerateAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Generate");
		w1.Add (this.GenerateAction, null);
		this.KeyAction = new global::Gtk.Action ("KeyAction", global::Mono.Unix.Catalog.GetString ("Key"), null, null);
		this.KeyAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Key");
		w1.Add (this.KeyAction, null);
		this.CertificateAction = new global::Gtk.Action ("CertificateAction", global::Mono.Unix.Catalog.GetString ("Certificate"), null, null);
		this.CertificateAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Certificate");
		w1.Add (this.CertificateAction, null);
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.ClearStatusBarAction = new global::Gtk.Action ("ClearStatusBarAction", global::Mono.Unix.Catalog.GetString ("Clear Status Bar"), null, null);
		this.ClearStatusBarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Clear Status Bar");
		w1.Add (this.ClearStatusBarAction, null);
		this.rubbishAction = new global::Gtk.Action ("rubbishAction", global::Mono.Unix.Catalog.GetString ("rubbish"), null, null);
		this.rubbishAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("rubbish");
		w1.Add (this.rubbishAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.StripPassphraseAction = new global::Gtk.Action ("StripPassphraseAction", global::Mono.Unix.Catalog.GetString ("Strip Passphrase"), null, null);
		this.StripPassphraseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Strip Passphrase");
		w1.Add (this.StripPassphraseAction, null);
		this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
		this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
		w1.Add (this.ToolsAction, null);
		this.WorkingDirectoryAction = new global::Gtk.Action ("WorkingDirectoryAction", global::Mono.Unix.Catalog.GetString ("Working Directory"), null, null);
		this.WorkingDirectoryAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Working Directory");
		w1.Add (this.WorkingDirectoryAction, null);
		this.ViewCertificateAction = new global::Gtk.Action ("ViewCertificateAction", global::Mono.Unix.Catalog.GetString ("View Certificate"), null, null);
		this.ViewCertificateAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View Certificate");
		w1.Add (this.ViewCertificateAction, null);
		this.CheckDiskAction = new global::Gtk.Action ("CheckDiskAction", global::Mono.Unix.Catalog.GetString ("Check Disk"), null, null);
		this.CheckDiskAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Check Disk");
		w1.Add (this.CheckDiskAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.WidthRequest = 600;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("SSLMaker");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("SSLMaker.images.padlockandkeys16x16.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='mainmenubar'><menu name='FileAction' action='FileAction'><menuitem name='LoadPrefsAction' action='LoadPrefsAction'/><menuitem name='SavePrefsAction' action='SavePrefsAction'/><menuitem name='QuitAction' action='QuitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='UserDetailsAction' action='UserDetailsAction'/><menuitem name='PreferencesAction' action='PreferencesAction'/><menuitem name='StripPassphraseAction' action='StripPassphraseAction'/></menu><menu name='GenerateAction' action='GenerateAction'><menuitem name='KeyAction' action='KeyAction'/><menuitem name='CertificateAction' action='CertificateAction'/></menu><menu name='ToolsAction' action='ToolsAction'><menuitem name='WorkingDirectoryAction' action='WorkingDirectoryAction'/><menuitem name='ViewCertificateAction' action='ViewCertificateAction'/><menuitem name='CheckDiskAction' action='CheckDiskAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.mainmenubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/mainmenubar")));
		this.mainmenubar.Name = "mainmenubar";
		this.vbox2.Add (this.mainmenubar);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.mainmenubar]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.image29 = new global::Gtk.Image ();
		this.image29.Name = "image29";
		this.image29.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SSLMaker.images.padlockandkeys80x80.png");
		this.hbox1.Add (this.image29);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image29]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(12));
		// Container child hbox1.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>SSLMaker v.0.9</b>\n\nCreated by D. Clayton");
		this.label1.UseMarkup = true;
		this.label1.Justify = ((global::Gtk.Justification)(2));
		this.hbox1.Add (this.label1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
		w4.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.image12 = new global::Gtk.Image ();
		this.image12.Name = "image12";
		this.image12.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SSLMaker.images.padlockandkeys80x80rev.png");
		this.hbox1.Add (this.image12);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image12]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		w5.Padding = ((uint)(12));
		this.vbox2.Add (this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox2.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hseparator1]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w8.Position = 0;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label ();
		this.label2.WidthRequest = 585;
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("An application that will create simple self-signed certificates including the corresponding key files.\nEdit the user details and the preferences to store the information required when creating the key/certificate files. These details will include your name and company details, cipher strength, etc.");
		this.label2.Wrap = true;
		this.label2.Justify = ((global::Gtk.Justification)(2));
		this.hbox7.Add (this.label2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label2]));
		w9.Position = 0;
		this.vbox1.Add (this.hbox7);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hseparator4 = new global::Gtk.HSeparator ();
		this.hseparator4.Name = "hseparator4";
		this.vbox5.Add (this.hseparator4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hseparator4]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		this.vbox3.Add (this.vbox5);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox5]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.hbox8.Add (this.fixed6);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixed6]));
		w13.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.WidthRequest = 450;
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
		this.frame1.BorderWidth = ((uint)(12));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 3;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.Xpad = 6;
		this.label3.Xalign = 0F;
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Key file</b>");
		this.label3.UseMarkup = true;
		this.vbox6.Add (this.label3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label3]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.lblKeyFileLocation = new global::Gtk.Label ();
		this.lblKeyFileLocation.Name = "lblKeyFileLocation";
		this.lblKeyFileLocation.Xpad = 6;
		this.lblKeyFileLocation.Xalign = 0F;
		this.lblKeyFileLocation.Yalign = 0F;
		this.lblKeyFileLocation.LabelProp = global::Mono.Unix.Catalog.GetString ("lblKeyFileLocation");
		this.hbox4.Add (this.lblKeyFileLocation);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.lblKeyFileLocation]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		w15.Padding = ((uint)(6));
		this.vbox6.Add (this.hbox4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox4]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.Xpad = 6;
		this.label4.Xalign = 0F;
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Certificate file</b>");
		this.label4.UseMarkup = true;
		this.vbox6.Add (this.label4);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label4]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.lblCertFileLocation = new global::Gtk.Label ();
		this.lblCertFileLocation.Name = "lblCertFileLocation";
		this.lblCertFileLocation.Xpad = 6;
		this.lblCertFileLocation.Xalign = 0F;
		this.lblCertFileLocation.Yalign = 0F;
		this.lblCertFileLocation.LabelProp = global::Mono.Unix.Catalog.GetString ("lblCertFileLocation");
		this.hbox5.Add (this.lblCertFileLocation);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblCertFileLocation]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		w18.Padding = ((uint)(6));
		this.vbox6.Add (this.hbox5);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox5]));
		w19.Position = 3;
		w19.Expand = false;
		w19.Fill = false;
		this.GtkAlignment.Add (this.vbox6);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel6 = new global::Gtk.Label ();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.Xalign = 0F;
		this.GtkLabel6.Yalign = 0F;
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>File Locations</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel6;
		this.hbox8.Add (this.frame1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.frame1]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child hbox8.Gtk.Box+BoxChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.hbox8.Add (this.fixed5);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.fixed5]));
		w23.Position = 2;
		this.vbox4.Add (this.hbox8);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox8]));
		w24.Position = 0;
		w24.Expand = false;
		w24.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.fixed8 = new global::Gtk.Fixed ();
		this.fixed8.Name = "fixed8";
		this.fixed8.HasWindow = false;
		this.hbox9.Add (this.fixed8);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.fixed8]));
		w25.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.WidthRequest = 450;
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(2));
		this.frame2.BorderWidth = ((uint)(12));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.vbox7.Add (this.fixed3);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.fixed3]));
		w26.Position = 0;
		w26.Expand = false;
		w26.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.ebCommonName = new global::Gtk.Entry ();
		this.ebCommonName.WidthRequest = 270;
		this.ebCommonName.CanFocus = true;
		this.ebCommonName.Name = "ebCommonName";
		this.ebCommonName.IsEditable = true;
		this.ebCommonName.MaxLength = 40;
		this.ebCommonName.InvisibleChar = '•';
		this.ebCommonName.Xalign = 0.01F;
		this.hbox6.Add (this.ebCommonName);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.ebCommonName]));
		w27.Position = 0;
		w27.Padding = ((uint)(40));
		// Container child hbox6.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.hbox6.Add (this.fixed2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed2]));
		w28.Position = 1;
		w28.Expand = false;
		this.vbox7.Add (this.hbox6);
		global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox6]));
		w29.Position = 1;
		w29.Expand = false;
		w29.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.fixed9 = new global::Gtk.Fixed ();
		this.fixed9.Name = "fixed9";
		this.fixed9.HasWindow = false;
		this.hbox10.Add (this.fixed9);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.fixed9]));
		w30.Position = 0;
		// Container child hbox10.Gtk.Box+BoxChild
		this.btnGenerateCert = new global::Gtk.Button ();
		this.btnGenerateCert.CanFocus = true;
		this.btnGenerateCert.Name = "btnGenerateCert";
		this.btnGenerateCert.UseUnderline = true;
		this.btnGenerateCert.Label = global::Mono.Unix.Catalog.GetString ("Generate Certificate");
		this.hbox10.Add (this.btnGenerateCert);
		global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.btnGenerateCert]));
		w31.Position = 1;
		w31.Expand = false;
		w31.Fill = false;
		// Container child hbox10.Gtk.Box+BoxChild
		this.fixed11 = new global::Gtk.Fixed ();
		this.fixed11.Name = "fixed11";
		this.fixed11.HasWindow = false;
		this.hbox10.Add (this.fixed11);
		global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.fixed11]));
		w32.Position = 2;
		this.vbox7.Add (this.hbox10);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox10]));
		w33.Position = 2;
		w33.Expand = false;
		w33.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox3.Add (this.fixed1);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.fixed1]));
		w34.Position = 0;
		this.vbox7.Add (this.hbox3);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox3]));
		w35.Position = 3;
		w35.Expand = false;
		w35.Fill = false;
		this.GtkAlignment1.Add (this.vbox7);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel10 = new global::Gtk.Label ();
		this.GtkLabel10.Name = "GtkLabel10";
		this.GtkLabel10.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Name (CN) for Certificate</b>");
		this.GtkLabel10.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel10;
		this.hbox9.Add (this.frame2);
		global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.frame2]));
		w38.Position = 1;
		w38.Expand = false;
		w38.Fill = false;
		// Container child hbox9.Gtk.Box+BoxChild
		this.fixed7 = new global::Gtk.Fixed ();
		this.fixed7.Name = "fixed7";
		this.fixed7.HasWindow = false;
		this.hbox9.Add (this.fixed7);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.fixed7]));
		w39.Position = 2;
		this.vbox4.Add (this.hbox9);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox9]));
		w40.Position = 1;
		w40.Expand = false;
		w40.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator ();
		this.hseparator2.Name = "hseparator2";
		this.vbox4.Add (this.hseparator2);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator2]));
		w41.Position = 2;
		w41.Expand = false;
		w41.Fill = false;
		w41.Padding = ((uint)(4));
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		// Container child hbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button ();
		this.button1.WidthRequest = 80;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		// Container child button1.Gtk.Container+ContainerChild
		global::Gtk.Alignment w42 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w43 = new global::Gtk.HBox ();
		w43.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w44 = new global::Gtk.Image ();
		w44.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-quit", global::Gtk.IconSize.Menu);
		w43.Add (w44);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w46 = new global::Gtk.Label ();
		w46.LabelProp = global::Mono.Unix.Catalog.GetString ("Done");
		w46.UseUnderline = true;
		w43.Add (w46);
		w42.Add (w43);
		this.button1.Add (w42);
		this.hbox2.Add (this.button1);
		global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.button1]));
		w50.PackType = ((global::Gtk.PackType)(1));
		w50.Position = 0;
		w50.Expand = false;
		w50.Fill = false;
		w50.Padding = ((uint)(6));
		this.vbox4.Add (this.hbox2);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
		w51.Position = 3;
		w51.Expand = false;
		w51.Fill = false;
		this.vbox3.Add (this.vbox4);
		global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
		w52.Position = 1;
		w52.Expand = false;
		w52.Fill = false;
		this.vbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox3]));
		w53.Position = 2;
		w53.Expand = false;
		w53.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.statusbar1.HasResizeGrip = false;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w54.Position = 3;
		w54.Expand = false;
		w54.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 652;
		this.DefaultHeight = 612;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.LoadPrefsAction.Activated += new global::System.EventHandler (this.OnLoadPrefsActionActivated);
		this.SavePrefsAction.Activated += new global::System.EventHandler (this.OnSavePrefsActionActivated);
		this.QuitAction.Activated += new global::System.EventHandler (this.onFileQuit_clicked);
		this.UserDetailsAction.Activated += new global::System.EventHandler (this.onEditUserDetails_clicked);
		this.PreferencesAction.Activated += new global::System.EventHandler (this.onEditPreferences_clicked);
		this.KeyAction.Activated += new global::System.EventHandler (this.onGenerateKey_clicked);
		this.CertificateAction.Activated += new global::System.EventHandler (this.onGenerateCertificate_clicked);
		this.ClearStatusBarAction.Activated += new global::System.EventHandler (this.OnClearStatusBarActionActivated);
		this.rubbishAction.Activated += new global::System.EventHandler (this.OnRubbishActionActivated);
		this.AboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
		this.StripPassphraseAction.Activated += new global::System.EventHandler (this.OnStripPassphraseActionActivated);
		this.WorkingDirectoryAction.Activated += new global::System.EventHandler (this.OnWorkingDirectoryActionActivated);
		this.ViewCertificateAction.Activated += new global::System.EventHandler (this.OnViewCertificateActionActivated);
		this.CheckDiskAction.Activated += new global::System.EventHandler (this.OnCheckDiskActionActivated);
		this.ebCommonName.Changed += new global::System.EventHandler (this.OnEbCommonNameChanged);
		this.btnGenerateCert.Clicked += new global::System.EventHandler (this.onGenerateCertificate_clicked);
		this.button1.Clicked += new global::System.EventHandler (this.onMainWinDone_clicked);
	}
}
