
// This file has been generated by the GUI designer. Do not modify.
namespace SSLMaker
{
	public partial class UserDetails
	{
		private global::Gtk.VBox vbox7;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Image image30;
		private global::Gtk.Label label11;
		private global::Gtk.HSeparator hseparator6;
		private global::Gtk.Label label18;
		private global::Gtk.HSeparator hseparator7;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label label12;
		private global::Gtk.Entry ebUDCountry;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label label13;
		private global::Gtk.Entry ebUDState;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Label label14;
		private global::Gtk.Entry ebUDLocality;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label label15;
		private global::Gtk.Entry ebUDOrgName;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Label label16;
		private global::Gtk.Entry ebUDOrgUnit;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Label label17;
		private global::Gtk.Entry ebUDEmail;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SSLMaker.UserDetails
			this.Name = "SSLMaker.UserDetails";
			this.Title = "";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("SSLMaker.images.padlockandkeys16x16.jpg");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child SSLMaker.UserDetails.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.image30 = new global::Gtk.Image ();
			this.image30.Name = "image30";
			this.image30.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SSLMaker.images.user.png");
			this.hbox4.Add (this.image30);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.image30]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>User Details</b>");
			this.label11.UseMarkup = true;
			this.hbox4.Add (this.label11);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label11]));
			w3.Position = 1;
			this.vbox7.Add (this.hbox4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox4]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator ();
			this.hseparator6.Name = "hseparator6";
			this.vbox7.Add (this.hseparator6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hseparator6]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Please enter details in the fields below. These will include you location and e-mail address.");
			this.label18.Wrap = true;
			this.vbox7.Add (this.label18);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.label18]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator7 = new global::Gtk.HSeparator ();
			this.hseparator7.Name = "hseparator7";
			this.vbox7.Add (this.hseparator7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hseparator7]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.WidthRequest = 168;
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Country (C):");
			this.hbox5.Add (this.label12);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label12]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.ebUDCountry = new global::Gtk.Entry ();
			this.ebUDCountry.CanFocus = true;
			this.ebUDCountry.Name = "ebUDCountry";
			this.ebUDCountry.IsEditable = true;
			this.ebUDCountry.InvisibleChar = '•';
			this.hbox5.Add (this.ebUDCountry);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.ebUDCountry]));
			w9.Position = 1;
			this.vbox7.Add (this.hbox5);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox5]));
			w10.Position = 4;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.WidthRequest = 168;
			this.label13.Name = "label13";
			this.label13.Xalign = 1F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("State or Province (S):");
			this.hbox6.Add (this.label13);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label13]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.ebUDState = new global::Gtk.Entry ();
			this.ebUDState.CanFocus = true;
			this.ebUDState.Name = "ebUDState";
			this.ebUDState.IsEditable = true;
			this.ebUDState.InvisibleChar = '•';
			this.hbox6.Add (this.ebUDState);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.ebUDState]));
			w12.Position = 1;
			this.vbox7.Add (this.hbox6);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox6]));
			w13.Position = 5;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.WidthRequest = 168;
			this.label14.Name = "label14";
			this.label14.Xalign = 1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Locality (L):");
			this.hbox7.Add (this.label14);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label14]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ebUDLocality = new global::Gtk.Entry ();
			this.ebUDLocality.CanFocus = true;
			this.ebUDLocality.Name = "ebUDLocality";
			this.ebUDLocality.IsEditable = true;
			this.ebUDLocality.InvisibleChar = '•';
			this.hbox7.Add (this.ebUDLocality);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ebUDLocality]));
			w15.Position = 1;
			this.vbox7.Add (this.hbox7);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox7]));
			w16.Position = 6;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.WidthRequest = 168;
			this.label15.Name = "label15";
			this.label15.Xalign = 1F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Organization Name (O):");
			this.hbox8.Add (this.label15);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label15]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.ebUDOrgName = new global::Gtk.Entry ();
			this.ebUDOrgName.CanFocus = true;
			this.ebUDOrgName.Name = "ebUDOrgName";
			this.ebUDOrgName.IsEditable = true;
			this.ebUDOrgName.InvisibleChar = '•';
			this.hbox8.Add (this.ebUDOrgName);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.ebUDOrgName]));
			w18.Position = 1;
			this.vbox7.Add (this.hbox8);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox8]));
			w19.Position = 7;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.WidthRequest = 168;
			this.label16.Name = "label16";
			this.label16.Xalign = 1F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Organizational Unit (OU):");
			this.hbox9.Add (this.label16);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label16]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.ebUDOrgUnit = new global::Gtk.Entry ();
			this.ebUDOrgUnit.CanFocus = true;
			this.ebUDOrgUnit.Name = "ebUDOrgUnit";
			this.ebUDOrgUnit.IsEditable = true;
			this.ebUDOrgUnit.InvisibleChar = '•';
			this.hbox9.Add (this.ebUDOrgUnit);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.ebUDOrgUnit]));
			w21.Position = 1;
			this.vbox7.Add (this.hbox9);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox9]));
			w22.Position = 8;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.WidthRequest = 168;
			this.label17.Name = "label17";
			this.label17.Xalign = 1F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("E-mail Address (E):");
			this.hbox10.Add (this.label17);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label17]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.ebUDEmail = new global::Gtk.Entry ();
			this.ebUDEmail.CanFocus = true;
			this.ebUDEmail.Name = "ebUDEmail";
			this.ebUDEmail.IsEditable = true;
			this.ebUDEmail.InvisibleChar = '•';
			this.hbox10.Add (this.ebUDEmail);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.ebUDEmail]));
			w24.Position = 1;
			this.vbox7.Add (this.hbox10);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox10]));
			w25.Position = 9;
			w25.Expand = false;
			w25.Fill = false;
			w1.Add (this.vbox7);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox7]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Internal child SSLMaker.UserDetails.ActionArea
			global::Gtk.HButtonBox w27 = this.ActionArea;
			w27.Name = "dialog1_ActionArea";
			w27.Spacing = 10;
			w27.BorderWidth = ((uint)(5));
			w27.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			// Container child buttonCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w28 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w29 = new global::Gtk.HBox ();
			w29.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w30 = new global::Gtk.Image ();
			w30.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w29.Add (w30);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w32 = new global::Gtk.Label ();
			w32.LabelProp = global::Mono.Unix.Catalog.GetString ("_Cancel");
			w32.UseUnderline = true;
			w29.Add (w32);
			w28.Add (w29);
			this.buttonCancel.Add (w28);
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w36 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w27 [this.buttonCancel]));
			w36.Expand = false;
			w36.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w37 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w38 = new global::Gtk.HBox ();
			w38.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w39 = new global::Gtk.Image ();
			w39.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w38.Add (w39);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w41 = new global::Gtk.Label ();
			w41.LabelProp = global::Mono.Unix.Catalog.GetString ("_Save");
			w41.UseUnderline = true;
			w38.Add (w41);
			w37.Add (w38);
			this.buttonOk.Add (w37);
			this.AddActionWidget (this.buttonOk, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w45 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w27 [this.buttonOk]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 502;
			this.DefaultHeight = 399;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.onCancel_clicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.onSave_clicked);
		}
	}
}
