
// This file has been generated by the GUI designer. Do not modify.
namespace SSLMaker
{
	public partial class About
	{
		private global::Gtk.VBox vbox8;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Image image10;
		private global::Gtk.Label label8;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.Label label1;
		private global::Gtk.HSeparator hseparator6;
		private global::Gtk.Label label10;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SSLMaker.About
			this.Name = "SSLMaker.About";
			this.Title = "";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("SSLMaker.images.padlockandkeys16x16.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child SSLMaker.About.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.image10 = new global::Gtk.Image ();
			this.image10.Name = "image10";
			this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("SSLMaker.images.ssl_cert55x68.png");
			this.hbox3.Add (this.image10);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.image10]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>SSLMaker</b>\n\nAn application that will create simple self-signed certificates including the corresponding key files.");
			this.label8.UseMarkup = true;
			this.label8.Wrap = true;
			this.label8.Justify = ((global::Gtk.Justification)(2));
			this.hbox3.Add (this.label8);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label8]));
			w3.Position = 1;
			w3.Padding = ((uint)(12));
			this.vbox8.Add (this.hbox3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox8.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hseparator1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Edit the user details and the preferences to store the information required when creating the key/certificate files. These details will include your name and company details, cipher strength, etc.");
			this.label1.Wrap = true;
			this.label1.Justify = ((global::Gtk.Justification)(2));
			this.vbox8.Add (this.label1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label1]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hseparator6 = new global::Gtk.HSeparator ();
			this.hseparator6.Name = "hseparator6";
			this.vbox8.Add (this.hseparator6);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hseparator6]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Created by David Clayton\nVersion 0.9\ncopyright claymarda");
			this.label10.UseMarkup = true;
			this.label10.Wrap = true;
			this.label10.Justify = ((global::Gtk.Justification)(2));
			this.vbox8.Add (this.label10);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label10]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			w8.Padding = ((uint)(12));
			w1.Add (this.vbox8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox8]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Internal child SSLMaker.About.ActionArea
			global::Gtk.HButtonBox w10 = this.ActionArea;
			w10.Name = "dialog1_ActionArea";
			w10.Spacing = 10;
			w10.BorderWidth = ((uint)(5));
			w10.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w11 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w10 [this.buttonOk]));
			w11.Expand = false;
			w11.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 413;
			this.DefaultHeight = 312;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
