
// This file has been generated by the GUI designer. Do not modify.
namespace SSLMaker
{
	public partial class KeyCreate
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox15;
		private global::Gtk.Image image240;
		private global::Gtk.Label label2;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label3;
		private global::Gtk.Entry ebFilename;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label4;
		private global::Gtk.Entry ebPassphrase;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label5;
		private global::Gtk.Entry ebPassphraseConfirm;
		private global::Gtk.HSeparator hseparator9;
		private global::Gtk.Label label23;
		private global::Gtk.HSeparator hseparator8;
		private global::Gtk.Frame frame3;
		private global::Gtk.Alignment GtkAlignment2;
		private global::Gtk.HBox hbox14;
		private global::Gtk.RadioButton rbKeySize1;
		private global::Gtk.RadioButton rbKeySize2;
		private global::Gtk.Label GtkLabel4;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget SSLMaker.KeyCreate
			this.Name = "SSLMaker.KeyCreate";
			this.Title = "";
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("SSLMaker.images.padlockandkeys16x16.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child SSLMaker.KeyCreate.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.image240 = new global::Gtk.Image ();
			this.image240.Name = "image240";
			this.image240.Xpad = 6;
			this.image240.Ypad = 6;
			this.image240.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-authentication", global::Gtk.IconSize.Menu);
			this.hbox15.Add (this.image240);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.image240]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Create SSL Key File</b>");
			this.label2.UseMarkup = true;
			this.hbox15.Add (this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label2]));
			w3.Position = 1;
			this.vbox3.Add (this.hbox15);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox15]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox3.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hseparator3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.WidthRequest = 82;
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Filename:");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ebFilename = new global::Gtk.Entry ();
			this.ebFilename.CanFocus = true;
			this.ebFilename.Name = "ebFilename";
			this.ebFilename.IsEditable = true;
			this.ebFilename.InvisibleChar = '•';
			this.hbox1.Add (this.ebFilename);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ebFilename]));
			w7.Position = 1;
			this.vbox4.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 82;
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Passphrase:");
			this.hbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label4]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ebPassphrase = new global::Gtk.Entry ();
			this.ebPassphrase.CanFocus = true;
			this.ebPassphrase.Name = "ebPassphrase";
			this.ebPassphrase.IsEditable = true;
			this.ebPassphrase.InvisibleChar = '•';
			this.hbox2.Add (this.ebPassphrase);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ebPassphrase]));
			w10.Position = 1;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.WidthRequest = 82;
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Confirm:");
			this.hbox3.Add (this.label5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label5]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.ebPassphraseConfirm = new global::Gtk.Entry ();
			this.ebPassphraseConfirm.CanFocus = true;
			this.ebPassphraseConfirm.Name = "ebPassphraseConfirm";
			this.ebPassphraseConfirm.IsEditable = true;
			this.ebPassphraseConfirm.InvisibleChar = '•';
			this.hbox3.Add (this.ebPassphraseConfirm);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.ebPassphraseConfirm]));
			w13.Position = 1;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator9 = new global::Gtk.HSeparator ();
			this.hseparator9.Name = "hseparator9";
			this.vbox4.Add (this.hseparator9);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator9]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 3;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Selecting OK will generate a key file using the details specified above.");
			this.label23.Wrap = true;
			this.label23.Justify = ((global::Gtk.Justification)(2));
			this.vbox4.Add (this.label23);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label23]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hseparator8 = new global::Gtk.HSeparator ();
			this.hseparator8.Name = "hseparator8";
			this.vbox4.Add (this.hseparator8);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hseparator8]));
			w17.PackType = ((global::Gtk.PackType)(1));
			w17.Position = 5;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame3.BorderWidth = ((uint)(20));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.rbKeySize1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("1024 bits"));
			this.rbKeySize1.CanFocus = true;
			this.rbKeySize1.Name = "rbKeySize1";
			this.rbKeySize1.DrawIndicator = true;
			this.rbKeySize1.UseUnderline = true;
			this.rbKeySize1.BorderWidth = ((uint)(3));
			this.rbKeySize1.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox14.Add (this.rbKeySize1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.rbKeySize1]));
			w18.Position = 0;
			w18.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.rbKeySize2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("2048 bits"));
			this.rbKeySize2.CanFocus = true;
			this.rbKeySize2.Name = "rbKeySize2";
			this.rbKeySize2.DrawIndicator = true;
			this.rbKeySize2.UseUnderline = true;
			this.rbKeySize2.BorderWidth = ((uint)(3));
			this.rbKeySize2.Group = this.rbKeySize1.Group;
			this.hbox14.Add (this.rbKeySize2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.rbKeySize2]));
			w19.Position = 1;
			w19.Fill = false;
			this.GtkAlignment2.Add (this.hbox14);
			this.frame3.Add (this.GtkAlignment2);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Key size</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel4;
			this.vbox4.Add (this.frame3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.frame3]));
			w22.PackType = ((global::Gtk.PackType)(1));
			w22.Position = 6;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox3.Add (this.vbox4);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			w1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox3]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Internal child SSLMaker.KeyCreate.ActionArea
			global::Gtk.HButtonBox w25 = this.ActionArea;
			w25.Name = "dialog1_ActionArea";
			w25.Spacing = 10;
			w25.BorderWidth = ((uint)(5));
			w25.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			// Container child buttonCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w26 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w27 = new global::Gtk.HBox ();
			w27.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w28 = new global::Gtk.Image ();
			w28.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w27.Add (w28);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w30 = new global::Gtk.Label ();
			w30.LabelProp = global::Mono.Unix.Catalog.GetString ("_Cancel");
			w30.UseUnderline = true;
			w27.Add (w30);
			w26.Add (w27);
			this.buttonCancel.Add (w26);
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w34 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w25 [this.buttonCancel]));
			w34.Expand = false;
			w34.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w35 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w36 = new global::Gtk.HBox ();
			w36.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w37 = new global::Gtk.Image ();
			w37.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			w36.Add (w37);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w39 = new global::Gtk.Label ();
			w39.LabelProp = global::Mono.Unix.Catalog.GetString ("_Generate");
			w39.UseUnderline = true;
			w36.Add (w39);
			w35.Add (w36);
			this.buttonOk.Add (w35);
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w43 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w25 [this.buttonOk]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 374;
			this.DefaultHeight = 396;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.onDlgCancel_clicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.onDlgOk_clicked);
		}
	}
}
